server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver kube-dns.kube-system.svc.cluster.local valid=10s;

    location /api/ {
        set $backend http://backend:8080;
        proxy_pass $backend/api/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}