apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: event-ticketing
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "103205"
  POSTGRES_DB: eventticketing