apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: event-ticketing
type: Opaque
stringData:
  SECURITY_JWT_SECRET: 8f3e9c2a1b7d4f6e0a9c8b7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: Admin12345678Admin