services:
  postgres:
    image: postgres:16
    container_name: eventticketing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 103205
      POSTGRES_DB: eventticketing
    ports:
      - "5432:5432"
    volumes:
      - eventticketing_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  eventticketing_postgres_data:
